"""add meet_link to bookings

Revision ID: 514b9ad8f4b8
Revises: 5d5ced06983d
Create Date: 2026-07-10 02:12:27.852775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '514b9ad8f4b8'
down_revision: Union[str, None] = '5d5ced06983d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('meet_link', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'meet_link')
    # ### end Alembic commands ###
